version: '3.7'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapi
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Database=postgres;Username=postgres;Password=postgres

  database:
    image: postgres:latest
    container_name: webapi-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
