version: '3.4'

services:
  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_HTTPS_PORT: "44359"
      ASPNETCORE_APIBaseUrl: https://localhost:5001/api
    ports:
      - 44359:443

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_HTTPS_PORT: "5001"
      SQLCONNSTR_DBConnectionString: "Data Source=database;Initial Catalog=teste-aiko;User Id = sa; Password = SenhaTopJ123@#;"
    ports:
      - 5001:443
    depends_on:
      - mssql-server
    links:
      - "mssql-server:database"

  mssql-server:
    container_name: mssql-server
    hostname: mssql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=SenhaTopJ123@#
    ports:
        - 1433:1433