CREATE TABLE Linhas (
    LinhaId BIGSERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE LinhasParadas (
    LinhaParadaId BIGSERIAL PRIMARY KEY,
    LinhaId BIGINT NOT NULL,
    ParadaId BIGINT NOT NULL,
    FOREIGN KEY (LinhaId) REFERENCES Linhas(LinhaId) ON DELETE RESTRICT,
    FOREIGN KEY (ParadaId) REFERENCES Paradas(ParadaId) ON DELETE RESTRICT
);

CREATE TABLE Paradas (
    ParadaId BIGSERIAL PRIMARY KEY,
    Name VARCHAR(255),
    Latitude DOUBLE PRECISION NOT NULL,
    Longitude DOUBLE PRECISION NOT NULL
);

CREATE TABLE Veiculos (
    VeiculoId BIGSERIAL PRIMARY KEY,
    Name VARCHAR(255),
    Modelo VARCHAR(255),
    LinhaId BIGINT NOT NULL,
    FOREIGN KEY (LinhaId) REFERENCES Linhas(LinhaId) ON DELETE RESTRICT
);

CREATE TABLE PosicoesVeiculos (
    PosicaoVeiculoId BIGSERIAL PRIMARY KEY,
    Latitude DOUBLE PRECISION NOT NULL,
    Longitude DOUBLE PRECISION NOT NULL,
    VeiculoId BIGINT NOT NULL,
    FOREIGN KEY (VeiculoId) REFERENCES Veiculos(VeiculoId) ON DELETE RESTRICT
);
