// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransportePublico.Infra.Contexts;

#nullable disable

namespace TransportePublico.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240118134940_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinhaParada", b =>
                {
                    b.Property<long>("LinhasLinhaId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParadasParadaId")
                        .HasColumnType("bigint");

                    b.HasKey("LinhasLinhaId", "ParadasParadaId");

                    b.HasIndex("ParadasParadaId");

                    b.ToTable("LinhaParada");
                });

            modelBuilder.Entity("TransportePublico.Domain.Entity.Linhas.Linha", b =>
                {
                    b.Property<long>("LinhaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LinhaId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("LinhaId");

                    b.ToTable("Linhas");
                });

            modelBuilder.Entity("TransportePublico.Domain.Entity.LinhasParadas.LinhaParada", b =>
                {
                    b.Property<long>("LinhaParadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LinhaParadaId"));

                    b.Property<long>("LinhaId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParadaId")
                        .HasColumnType("bigint");

                    b.HasKey("LinhaParadaId");

                    b.HasIndex("LinhaId");

                    b.HasIndex("ParadaId");

                    b.ToTable("LinhasParadas");
                });

            modelBuilder.Entity("TransportePublico.Domain.Entity.Paradas.Parada", b =>
                {
                    b.Property<long>("ParadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ParadaId"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ParadaId");

                    b.ToTable("Paradas");
                });

            modelBuilder.Entity("TransportePublico.Domain.Entity.PosicoesVeiculos.PosicaoVeiculo", b =>
                {
                    b.Property<long>("PosicaoVeiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PosicaoVeiculoId"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<long>("VeiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("PosicaoVeiculoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("PosicoesVeiculos");
                });

            modelBuilder.Entity("TransportePublico.Domain.Entity.Veiculos.Veiculo", b =>
                {
                    b.Property<long>("VeiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VeiculoId"));

                    b.Property<long>("LinhaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("VeiculoId");

                    b.HasIndex("LinhaId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("LinhaParada", b =>
                {
                    b.HasOne("TransportePublico.Domain.Entity.Linhas.Linha", null)
                        .WithMany()
                        .HasForeignKey("LinhasLinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportePublico.Domain.Entity.Paradas.Parada", null)
                        .WithMany()
                        .HasForeignKey("ParadasParadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TransportePublico.Domain.Entity.LinhasParadas.LinhaParada", b =>
                {
                    b.HasOne("TransportePublico.Domain.Entity.Linhas.Linha", "Linha")
                        .WithMany("LinhasParadas")
                        .HasForeignKey("LinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportePublico.Domain.Entity.Paradas.Parada", "Parada")
                        .WithMany("LinhasParadas")
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linha");

                    b.Navigation("Parada");
                });

            modelBuilder.Entity("TransportePublico.Domain.Entity.PosicoesVeiculos.PosicaoVeiculo", b =>
                {
                    b.HasOne("TransportePublico.Domain.Entity.Veiculos.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("TransportePublico.Domain.Entity.Veiculos.Veiculo", b =>
                {
                    b.HasOne("TransportePublico.Domain.Entity.Linhas.Linha", "Linha")
                        .WithMany()
                        .HasForeignKey("LinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linha");
                });

            modelBuilder.Entity("TransportePublico.Domain.Entity.Linhas.Linha", b =>
                {
                    b.Navigation("LinhasParadas");
                });

            modelBuilder.Entity("TransportePublico.Domain.Entity.Paradas.Parada", b =>
                {
                    b.Navigation("LinhasParadas");
                });
#pragma warning restore 612, 618
        }
    }
}
