name: Build and deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    env:
      CAMINHO_PROJETO_TESTES: ./src/Tests/Tests.csproj
      CAMINHO_PROJETO_API: ./src/Api/Api.csproj
      CAMINHO_PROJETO_WEBUI: ./src/WebUI/WebUI.csproj
      NOME_WEBAPI_AZURE: apidesafioaikodigital
      NOME_WEBUI_AZURE: desafioaikodigital

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build Api
      run: dotnet build ${{ env.CAMINHO_PROJETO_API }} --configuration Release
   
    - name: Build WebUI
      run: dotnet build ${{ env.CAMINHO_PROJETO_WEBUI }} --configuration Release
    
    - name: Run Tests
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal
      
    - name: Publish Api
      run: dotnet publish ${{ env.CAMINHO_PROJETO_API }} -c Release -o app
      
    - name: Publish WebUI
      run: dotnet publish ${{ env.CAMINHO_PROJETO_WEBUI }} -c Release -o app

    - name: Login no Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.API_CREDENTIALS }}
    
    - name: Deployment Api no Azure App Service
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.NOME_WEBAPI_AZURE }}
        package: './app'
  
    - name: Deployment WebUI no Azure App Service
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.NOME_WEBUI_AZURE }}
        package: './app'