name: Build and deploy WebUI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    env:
      CAMINHO_PROJETO_WEBUI: ./src/WebUI/WebUI.csproj
      NOME_WEBUI_AZURE: desafioaikodigital

    runs: 
        using: 'docker'
        image: 'Dockerfile'

    steps:
    - uses: actions/checkout@main
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build WebUI
      run: dotnet build ${{ env.CAMINHO_PROJETO_WEBUI }} --configuration Release
    
    - name: Publish WebUI
      run: dotnet publish ${{ env.CAMINHO_PROJETO_WEBUI }} -c Release -o app
          
    - name: Login Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.WEBUI_CREDENTIALS }}

    - name: Deployment WebUI no Azure App Service
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.NOME_WEBUI_AZURE }}
        package: './app'