name: Build and deploy WebUI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    env:
      CAMINHO_PROJETO_WEBUI: ./src/WebUI/WebUI.csproj
      NOME_WEBUI_AZURE: desafioaikodigital

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build WebUI
      run: dotnet build ${{ env.CAMINHO_PROJETO_WEBUI }} --configuration Release
    
    - name: Publish WebUI
      run: dotnet publish ${{ env.CAMINHO_PROJETO_WEBUI }} -c Release -o app
          
    - name: Docker Login - Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

    - name: Build e Push no Azure Container Registry
      run: |
        docker build -t ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/webui:latest -f src/WebUI/Dockerfile .
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/webui:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/webui:$(date +%s)
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/webui:latest